ExamScheduler/Controllers/CampusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExamScheduler;

namespace ExamScheduler.Controllers
{
    public class CampusController : Controller
    {
        private ExamSchedulerDbEntities db = new ExamSchedulerDbEntities();

        // GET: Campus
        public ActionResult Index()
        {
            return View(db.Campus1.ToList());
        }

        // GET: Campus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campus campus = db.Campus1.Find(id);
            if (campus == null)
            {
                return HttpNotFound();
            }
            return View(campus);
        }

        // GET: Campus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Campus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CampusID,Name")] Campus campus)
        {
            if (ModelState.IsValid)
            {
                db.Campus1.Add(campus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(campus);
        }

        // GET: Campus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campus campus = db.Campus1.Find(id);
            if (campus == null)
            {
                return HttpNotFound();
            }
            return View(campus);
        }

        // POST: Campus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CampusID,Name")] Campus campus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(campus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(campus);
        }

        // GET: Campus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campus campus = db.Campus1.Find(id);
            if (campus == null)
            {
                return HttpNotFound();
            }
            return View(campus);
        }

        // POST: Campus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Campus campus = db.Campus1.Find(id);
            db.Campus1.Remove(campus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExamScheduler/Controllers/ScheduledExamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using ExamScheduler;

namespace ExamScheduler.Controllers
{
    public class ScheduledExamsController : Controller
    {
        private ExamSchedulerDbEntities db = new ExamSchedulerDbEntities();

        // GET: ScheduledExams
        public ActionResult Index()
        {
            var scheduledExams = db.ScheduledExams.Include(s => s.Campu).Include(s => s.Course).Include(s => s.ExamStage).Include(s => s.Room);
            return View(scheduledExams.ToList());
        }

        // GET: ScheduledExams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ScheduledExam scheduledExam = db.ScheduledExams.Find(id);
            if (scheduledExam == null)
            {
                return HttpNotFound();
            }
            return View(scheduledExam);
        }

        // GET: ScheduledExams/Create
        public ActionResult Create()
        {
            ViewBag.CampusID = new SelectList(db.Campus1, "CampusID", "Name");
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Name");
            ViewBag.ExamStageID = new SelectList(db.ExamStages, "ExamStageID", "Name");
            ViewBag.RoomID = new SelectList(db.Rooms, "RoomID", "Name");
            return View();
        }

        // POST: ScheduledExams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ScheduledExamID,CourseID,RoomID,Name,CampusID,ExamStageID,Date,StartTime,EndTime")] ScheduledExam scheduledExam)
        {
            if (ModelState.IsValid)
            {
                // Load related entities to generate the name
                scheduledExam.Course = db.Courses.Find(scheduledExam.CourseID);
                scheduledExam.ExamStage = db.ExamStages.Find(scheduledExam.ExamStageID);
                scheduledExam.Campu = db.Campus1.Find(scheduledExam.CampusID);
                scheduledExam.Room = db.Rooms.Find(scheduledExam.RoomID);
                
                db.ScheduledExams.Add(scheduledExam);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CampusID = new SelectList(db.Campus1, "CampusID", "Name", scheduledExam.CampusID);
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Name", scheduledExam.CourseID);
            ViewBag.ExamStageID = new SelectList(db.ExamStages, "ExamStageID", "Name", scheduledExam.ExamStageID);
            ViewBag.RoomID = new SelectList(db.Rooms, "RoomID", "Name", scheduledExam.RoomID);
            return View(scheduledExam);
        }

        // GET: ScheduledExams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ScheduledExam scheduledExam = db.ScheduledExams.Find(id);
            if (scheduledExam == null)
            {
                return HttpNotFound();
            }
            ViewBag.CampusID = new SelectList(db.Campus1, "CampusID", "Name", scheduledExam.CampusID);
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Name", scheduledExam.CourseID);
            ViewBag.ExamStageID = new SelectList(db.ExamStages, "ExamStageID", "Name", scheduledExam.ExamStageID);
            ViewBag.RoomID = new SelectList(db.Rooms, "RoomID", "Name", scheduledExam.RoomID);
            return View(scheduledExam);
        }

        // POST: ScheduledExams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ScheduledExamID,CourseID,RoomID,Name,CampusID,ExamStageID,Date,StartTime,EndTime")] ScheduledExam scheduledExam)
        {
            if (ModelState.IsValid)
            {
                // Load related entities to generate the name
                scheduledExam.Course = db.Courses.Find(scheduledExam.CourseID);
                scheduledExam.ExamStage = db.ExamStages.Find(scheduledExam.ExamStageID);
                scheduledExam.Campu = db.Campus1.Find(scheduledExam.CampusID);
                scheduledExam.Room = db.Rooms.Find(scheduledExam.RoomID);
                
                db.Entry(scheduledExam).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CampusID = new SelectList(db.Campus1, "CampusID", "Name", scheduledExam.CampusID);
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Name", scheduledExam.CourseID);
            ViewBag.ExamStageID = new SelectList(db.ExamStages, "ExamStageID", "Name", scheduledExam.ExamStageID);
            ViewBag.RoomID = new SelectList(db.Rooms, "RoomID", "Name", scheduledExam.RoomID);
            return View(scheduledExam);
        }

        // GET: ScheduledExams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ScheduledExam scheduledExam = db.ScheduledExams.Find(id);
            if (scheduledExam == null)
            {
                return HttpNotFound();
            }
            return View(scheduledExam);
        }

        // POST: ScheduledExams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ScheduledExam scheduledExam = db.ScheduledExams.Find(id);
            db.ScheduledExams.Remove(scheduledExam);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExamScheduler/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("EXAM SCHEDULER", "Index", "ScheduledExams", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Users", "Index", "Users", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("ScheduledExams", "index", "ScheduledExams", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("ScheduledExamStudents", "Index", "ScheduledExamStudents", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("ScheduledExamProcters", "Index", "ScheduledExamProcters", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Rooms", "Index", "Rooms", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Roles", "Index", "Roles", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("ExamStages", "Index", "ExamStages", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Courses", "Index", "Courses", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Campuses", "Index", "Campus", new { area = "" }, new { @class = "nav-link" })</li>


                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    
    <!-- DataTables CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">
    
    <!-- DataTables JS -->
    <script type="text/javascript" src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
    
    <script>
        $(document).ready(function() {
            $('.datatable').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'excel'
                ],
                pageLength: 25,
                order: [[0, 'asc']]
            });
        });
    </script>
    
    @RenderSection("scripts", required: false)
</body>
</html>